#ifndef FLAGS_H_INCLUDED
#define FLAGS_H_INCLUDED

enum errorFlags{
    PARSER_CANNOT_OPEN_FILE = 10,
    PARSER_CANNOT_MAKE_REGEX,

    WATCHDOG_CANNOT_OPEN_DIR = 20,
    WATCHDOG_CANNOT_FIND_CALLBACKS,
    WATCHDOG_CANNOT_LOAD_CALLBACKS,
};

#endif // FLAGS_H_INCLUDED
