#ifndef FLAGS_H_INCLUDED
#define FLAGS_H_INCLUDED

enum errorFlags{
    PARSER_CANNOT_OPEN_FILE = 10,

    WATCHDOG_CANNOT_OPEN_DIR = 20,
    WATCHDOG_CANNOT_FIND_CALLBACKS,
    WATCHDOG_CANNOT_LOAD_CALLBACKS,
    WATCHDOG_CANNOT_LOAD_LOGFILE,
    WATCHDOG_CANNOT_PROCESS_CALLBACK,

    WATCHDOG_CALLBACK_ABORT,
    WATCHDOG_ABORT
};

#endif // FLAGS_H_INCLUDED
